// Extract link annotations from a PDF and emit LaTeX overlays for pdfpages.
//
// WHY: \includepdf includes pages as graphics and discards their annotations, so
// every hyperlink in the CV is dead inside the dissertation. The usual remedy is
// the pax package, but its extractor (pdfannotextractor) needs a Java runtime.
// This does the same job with PDFKit, which is already on every macOS machine.
//
// Reads : cv.pdf
// Writes: cv-links.tex, defining \CVlinks{<page>} for each page that has links.
//         endmatter/cv.tex calls it from \includepdf's pagecommand, which
//         re-creates the links as real annotations on top of the placed page.
//
// Coordinates come straight from the source PDF in points, which is valid
// because the CV pages are the same 612x792 size as the dissertation and are
// placed 1:1 (fitpaper=false, offset 0 0). If that ever changes, this breaks
// visibly rather than silently: the boxes land in the wrong place.
//
// Usage: extract-links <in.pdf> <out.tex>

import Foundation
import PDFKit

let args = CommandLine.arguments
guard args.count >= 3 else {
    FileHandle.standardError.write("usage: extract-links <in.pdf> <out.tex>\n".data(using: .utf8)!)
    exit(2)
}
guard let doc = PDFDocument(url: URL(fileURLWithPath: args[1])) else {
    FileHandle.standardError.write("cannot open \(args[1])\n".data(using: .utf8)!)
    exit(1)
}

/// Escape a URL for use in a LaTeX argument.
func texEscape(_ s: String) -> String {
    var out = ""
    for ch in s {
        switch ch {
        case "\\": out += "\\textbackslash{}"
        case "{", "}", "$", "&", "#", "^", "_", "~", "%":
            out += "\\string" + String(ch)
        default: out.append(ch)
        }
    }
    return out
}

var body = ""
var total = 0

for i in 0..<doc.pageCount {
    guard let page = doc.page(at: i) else { continue }
    var puts: [String] = []
    for a in page.annotations {
        let url = a.url?.absoluteString
            ?? (a.action as? PDFActionURL)?.url?.absoluteString
        guard let url, !url.isEmpty else { continue }
        let r = a.bounds
        guard r.width > 0.1, r.height > 0.1 else { continue }
        // \put places the box with its baseline-left at (x,y); the invisible
        // strut below is r.width wide and r.height tall with no depth, so it
        // spans exactly minY..maxY.
        puts.append(String(
            format: "  \\put(%.2f,%.2f){\\href{%@}{\\hspace*{%.2fpt}\\rule{0pt}{%.2fpt}}}%%",
            r.minX, r.minY, texEscape(url) as NSString, r.width, r.height))
        total += 1
    }
    if puts.isEmpty { continue }
    body += "\\expandafter\\gdef\\csname CVlinks@\(i + 1)\\endcsname{%\n"
    body += "  \\AddToShipoutPictureFG*{\\AtPageLowerLeft{%\n"
    body += puts.joined(separator: "\n") + "\n"
    body += "  }}%\n}\n"
}

var out = """
% ---------------------------------------------------------------------------
% AUTO-GENERATED by document/cv/extract-links.swift -- do not edit by hand.
% Regenerate with: bash document/cv/build-cv.sh
%
% Recreates the hyperlinks of graphics/cv.pdf as real annotations on top of the
% pages placed by \\includepdf, which discards the originals.
% \(total) link(s) across \(doc.pageCount) page(s).
% ---------------------------------------------------------------------------
% \\CVlinks{n} is a no-op for pages that carry no links.
\\providecommand{\\CVlinks}[1]{%
  \\ifcsname CVlinks@#1\\endcsname\\csname CVlinks@#1\\endcsname\\fi
}

"""
out += body

do {
    try out.write(toFile: args[2], atomically: true, encoding: .utf8)
    print("extract-links: \(total) link(s) -> \(args[2])")
} catch {
    FileHandle.standardError.write("write failed: \(error)\n".data(using: .utf8)!)
    exit(1)
}
